services:
  postgres:
    image: postgres:15-alpine
    container_name: local_postgres
    environment:
      POSTGRES_DB: service_matching
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 10101978
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: on-failure

  redis:
    image: redis:7-alpine
    container_name: local_redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: on-failure

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: cohangxom_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      OLLAMA_HOST: "0.0.0.0"
    networks:
      - cohangxom_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434/api/tags" ]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  ollama_data:
    driver: local

networks:
  app-network:
    driver: bridge
  cohangxom_network:
    driver: bridge
