export const QUOTE_CONSTANTS = {
    MIN_PRICE: 10000,
    MAX_PRICE: 100000000, 

    MAX_PRICE_RATIO_TO_BUDGET: 1.5, 

    MIN_ESTIMATED_DURATION: 30, 
    MAX_ESTIMATED_DURATION: 43200, 

    MAX_QUOTES_PER_POST: 50, 
    MAX_ACTIVE_QUOTES_PER_PROVIDER: 100, 

    AUTO_REJECT_QUOTE_DAYS: 7, 
    QUOTE_EDIT_TIMEOUT_MINUTES: 30, 
} as const;