export enum AuthErrorCode {
    EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
    PHONE_ALREADY_REGISTERED = 'PHONE_ALREADY_REGISTERED',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
    TOKEN_REUSE_DETECTED = 'TOKEN_REUSE_DETECTED',
    DEVICES_NOT_FOUND = 'DEVICES_NOT_FOUND'
}