export const AUTH_CONSTANTS = {
    BCRYPT_ROUNDS: 12,
    REFRESH_TOKEN_BCRYPT_ROUNDS: 10,
    REFRESH_TOKEN_EXPIRY_DAYS: 7,
    MAX_REFRESH_TOKENS_PER_USER: 5,
    MAX_REFRESH_TOKENS_PER_DEVICE: 3,
    TOKEN_CLEANUP_BATCH_SIZE: 1000,
    MAX_LOGIN_ATTEMPTS: 5,
    LOGIN_LOCKOUT_DURATION_MINUTES: 15,

    // Password
    PASSWORD_MIN_LENGTH: 8,
    PASSWORD_MIN_UPPERCASE: 1,
    PASSWORD_MIN_LOWERCASE: 1,
    PASSWORD_MIN_NUMBERS: 1,
    PASSWORD_MIN_SYMBOLS: 1,
} as const;

export const AUTH_ERROR_CODES = {
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
    INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
    DEVICE_ID_REQUIRED: 'DEVICE_ID_REQUIRED',
    INVALID_DEVICE_ID: 'INVALID_DEVICE_ID',
    WEAK_PASSWORD: 'WEAK_PASSWORD',
    REFRESH_TOKEN_MISSING: 'REFRESH_TOKEN_MISSING',
    REFRESH_TOKEN_NOT_FOUND:'REFRESH_TOKEN_NOT_FOUND'
} as const;