export const NOTIFICATION_CONSTANTS = {
    DEFAULT_PAGE_SIZE: 20,
    MAX_PAGE_SIZE: 100,

   
    DELETE_READ_AFTER_DAYS: 30, 
    DELETE_UNREAD_AFTER_DAYS: 90, 

    MAX_NOTIFICATIONS_PER_BATCH: 1000,

    MAX_NOTIFICATIONS_PER_USER_PER_HOUR: 100,
} as const;